# 1.1 - NumPy - Introdução

In [44]:
import numpy as np

1. Obtenha a versão numpy e mostre a configuração de compilação numpy. 

In [45]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/raquel.ribeiro/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/raquel.ribeiro/Ana

In [46]:
#para a versão também podemos usar
np.version.version

'1.21.5'

2. Obtenha ajuda na função de adição. 

In [47]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Teste se nenhum dos elementos dos seguinte arrays é zero. 
	X1 = [1,2,3,4]
	X2 = [0,1,2,3]

In [48]:
x = np.array([1, 2, 3, 4])
print("array original:")
print(x)
print("Testar se nenhum dos elementos é zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("array original:")
print(x)
print("Testar se nenhum dos elementos é zero:")
print(np.all(x))

array original:
[1 2 3 4]
Testar se nenhum dos elementos é zero:
True
array original:
[0 1 2 3]
Testar se nenhum dos elementos é zero:
False


4. Teste se algum dos elementos dos arrays X1 e X2 é diferente de zero. 

In [49]:
x = np.array([1, 0, 0, 0])
print("array original:")
print(x)
print("Testar se algum dos elementos é diferente de zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("array original:")
print(x)
print("Testar se algum dos elementos é diferente de zero:")
print(np.any(x))

array original:
[1 0 0 0]
Testar se algum dos elementos é diferente de zero:
True
array original:
[0 0 0 0]
Testar se algum dos elementos é diferente de zero:
False


5. Teste se os elementos do seguinte array são finitos (não infinito ou não um número). 
	X3 = [1,0,nan,inf]

In [50]:
a = np.array([1, 0, np.nan, np.inf])
print("array original:")
print(a)
print("Testar se os elementos do seguinte array são finitos :")
print(np.isfinite(a))

array original:
[ 1.  0. nan inf]
Testar se os elementos do seguinte array são finitos :
[ True  True False False]


6. Teste elemento a elemento de X3 se é infinito. 

In [51]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("array original:")
print(a)
print("Testar elemento a elemento de X3 se é infinito:")
print(np.isinf(a))

array original:
[ 1.  0. nan inf]
Testar elemento a elemento de X3 se é infinito:
[False False False  True]


7. Teste elemento a elemento de X3 se é NaN. 

In [52]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("array original:")
print(a)
print("Testar elemento a elemento de X3 se é NaN:")
print(np.isnan(a))

array original:
[ 1.  0. nan inf]
Testar elemento a elemento de X3 se é NaN:
[False False  True False]


8. Crie uma comparação elemento a elemento (maior, maior ou igual, menor e menor ou igual) dos seguintes arrays. 
	X4 = [1,6,4,3,6,9]
	X5 = [3,4,6,3,6,4]

In [53]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Números originais:")
print(x)
print(y)
print("Comaparação - maior")
print(np.greater(x, y))
print("Comparação - maior ou igual")
print(np.greater_equal(x, y))
print("Comparação - menor")
print(np.less(x, y))
print("Comparação - menor ou igual")
print(np.less_equal(x, y))

Números originais:
[3 5]
[2 5]
Comaparação - maior
[ True False]
Comparação - maior ou igual
[ True  True]
Comparação - menor
[False False]
Comparação - menor ou igual
[False  True]


9. Crie uma comparação elemento a elemento (igual, igual dentro de uma tolerância) dos seguintes arrays.
	X6 = [72, 79, 85, 90, 150, -135, 120, -10, 60, 100]
	X7 = [72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001]

In [54]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Números originais:")
print(x)
print(y)
print("Comparação - igual:")
print(np.equal(x, y))
print("Comparação com uma tolerância:")
print(np.allclose(x, y))

Números originais:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparação - igual:
[ True  True  True  True  True  True  True  True  True False]
Comparação com uma tolerância:
True


10. Crie um array com os valores 1, 7, 13, 105 e determine o tamanho da memória ocupada pelo array. 

In [55]:
X = np.array([1, 7, 13, 105])
print("array original:")
print(X)
print("Tamanho ocupado pelo array:")
print("%d bytes" % (X.size * X.itemsize))

array original:
[  1   7  13 105]
Tamanho ocupado pelo array:
16 bytes


11. Crie um array de 10 zeros, 10 uns, 10 cincos. 

In [56]:
array=np.zeros(10)
print("Um array de 10 zeros:")
print(array)
array=np.ones(10)
print("Um array de 10 ones:")
print(array)
array=np.ones(10)*5
print("Um array de 10 fives:")
print(array)

Um array de 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Um array de 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Um array de 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


12. Crie um array de inteiros de 30 a 70. 

In [57]:
array=np.arange(30,71)
print("Array de inteiros de 30 a 70")
print(array)

Array de inteiros de 30 a 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


13. Crie um array de todos os inteiros pares de 30 a 70. 

In [58]:
array=np.arange(30,71,2)
print("Array com todos os inteiros pares entre 30 e 70")
print(array) 

Array com todos os inteiros pares entre 30 e 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


14. Crie uma matriz identidade 3x3. 

In [59]:
array_2D=np.identity(3)
print('matriz 3x3:')
print(array_2D)

matriz 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15. Gere um número aleatório entre 0 e 1. 

In [60]:
array_2D=np.identity(3)
print('matriz 3x3:')
print(array_2D)

matriz 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


16. Gere um array de 15 números aleatórios de uma distribuição normal padrão. 

In [61]:
rand_num = np.random.normal(0,1,15)
print("15 números aleatórios de uma distribuição normal:")
print(rand_num)

15 números aleatórios de uma distribuição normal:
[ 0.34928073  1.16734163  0.3489526   0.82803034 -1.04939401 -0.56631462
  0.42980349  0.06537119  2.33096984 -1.19046504 -0.10406276 -0.70299109
 -0.8705411   1.74957218 -2.24455941]


17. Crie um array com valores variando de 15 a 55 e imprima todos os valores. Depois imprima todos exceto o primeiro e o último. 

In [62]:
v = np.arange(15,55)
print("vector original:")
print(v)
print("todos exceto o primeiro e o último:")
print(v[1:-1])

vector original:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
todos exceto o primeiro e o último:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


18. Crie uma matriz 3X4 com valores de 10 a 22. Depois itere sobre ele. 

In [63]:
a = np.arange(10,22).reshape((3, 4))
print("array original:")
print(a)
print("Cada elemento do array é:")
for x in np.nditer(a):
  print(x,end=" ")

array original:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Cada elemento do array é:
10 11 12 13 14 15 16 17 18 19 20 21 

19. Crie um array de comprimento 10 com valores uniformemente distribuídos entre 5 e 50. 

In [64]:
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


20. Crie um array com valores de 0 a 20 e altere o sinal dos números no intervalo de 9 a 15. 

In [65]:
x = np.arange(21)
print("vetor original:")
print(x)
print("alterar o sinal dos números no intervalo de 9 a 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

vetor original:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
alterar o sinal dos números no intervalo de 9 a 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


21. Crie um array de comprimento 5 preenchido com inteiros arbitrários de 0 a 10.  

In [66]:
x = np.random.randint(0, 11, 5)
print("array de comprimento 5 preenchido com inteiros arbitrários de 0 a 10:")
print(x)

array de comprimento 5 preenchido com inteiros arbitrários de 0 a 10:
[8 6 1 3 3]


22. Multiplique os valores de dois arrays dados. 
	X8 = [1,8,3,5]
	X9 = array de 4 elementos com valores inteiros aleatórios de 0 a 11

In [67]:
x = np.array([1, 8, 3, 5])
print("X8")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector aleatório")
print(y)
result = x * y
print("Multiplicar os valores dos dois vetores:")
print(result)

X8
[1 8 3 5]
Vector aleatório
[6 1 8 5]
Multiplicar os valores dos dois vetores:
[ 6  8 24 25]


23. Crie uma matriz 3x4 preenchida com valores de 10 a 21. 

In [68]:
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


24. Encontre o número de linhas e colunas da matriz anterior. 

In [69]:
m= np.arange(10,22).reshape((3, 4))
print("Matriz original:")
print(m)
print("Número de linhas e colunas da matriz:")
print(m.shape)

Matriz original:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Número de linhas e colunas da matriz:
(3, 4)


25. Crie uma matriz de identidade 3x3, ou seja, os elementos diagonais são 1, o restante é 0. 

In [70]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


26. Crie uma matriz 10x10, na qual os elementos nas pontas (1ª e última linha e coluna) são iguais a 1 e dentro de 0. 

In [71]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


27. Crie uma matriz zero 5x5 com elementos na diagonal principal igual a 1, 2, 3, 4, 5. 

In [72]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


28. Crie uma matriz 3x3x3 preenchida com valores aleatórios. 

In [73]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.05601915 0.93740501 0.11472203]
  [0.23962125 0.69196467 0.03624878]
  [0.49269473 0.66813399 0.28720754]]

 [[0.32692799 0.51791781 0.49548012]
  [0.93758687 0.88110604 0.99867892]
  [0.95891387 0.6014197  0.53360839]]

 [[0.20879398 0.57613979 0.35356294]
  [0.86129825 0.63765579 0.40721373]
  [0.85821086 0.66206855 0.5497152 ]]]


29. Calcule a soma de todos os elementos, a soma de cada coluna e a soma de cada linha da seguinte matriz.
 	M1 = 0 1
	     2 3 


In [74]:
x = np.array([[0,1],[2,3]])
print("Array original:")
print(x)
print("Soma de todos os elementos:")
print(np.sum(x))
print("Soma de cada coluna:")
print(np.sum(x, axis=0))
print("Soma de cada linha:")
print(np.sum(x, axis=1))

Array original:
[[0 1]
 [2 3]]
Soma de todos os elementos:
6
Soma de cada coluna:
[2 4]
Soma de cada linha:
[1 5]


30. Adicione o seguinte array a cada linha da seguinte matriz.
 	m2 = [[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]
	V1 = [1, 1, 0]

In [75]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Vector original:")
print(v)
print("Matriz original:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print(result)

Vector original:
[1 1 0]
Matriz original:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


31. Converta uma determinada lista numa matriz e converta novamente numa lista. Verifique se a lista inicial e a lista final são iguais ou não. 
	M3 = [[1,2],[3,4]]

In [76]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True
