# 1.1 - W NumPy - Indexação, seleção e operações

In [110]:
import numpy as np

#### 1.  Ordene a matriz m1 ao longo do primeiro eixo, último eixo e na matriz achatada em array. 
#### M1 =
#### [[10 40]
#### [30 20]]


In [111]:
a = np.array([[10,40],[30,20]])
print("array original:")
print(a)
print("Ordenar o array pelo primeiro eixo:")
print(np.sort(a, axis=0))
print("Ordenar o array pelo último eixo:")
print(np.sort(a))
print("Ordenar na matriz achatada:")
print(np.sort(a, axis=None))

array original:
[[10 40]
 [30 20]]
Ordenar o array pelo primeiro eixo:
[[10 20]
 [30 40]]
Ordenar o array pelo último eixo:
[[10 40]
 [20 30]]
Ordenar na matriz achatada:
[10 20 30 40]


#### 2.  Crie uma matriz estruturada a partir dos nomes do aluno, altura, classe e os seus tipos de dados. Agora ordene a matriz por altura. 
#### [(‘nome’, 'S15'), ('classe', int), ('altura', float)]
#### ('James', 5, 156.), ('Nail', 6, 172.),('Paul', 5, 173.), ('Pit', 5, 164.)



In [112]:
data_type = [('nome', 'S15'), ('classe', int), ('altura', float)]
students_details = [('James', 5, 156.), ('Nail', 6, 172.),('Paul', 5, 173.), ('Pit', 5, 164.)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("array original:")
print(students)
print("Ordenar por altura")
print(np.sort(students, order='altura'))    

array original:
[(b'James', 5, 156.) (b'Nail', 6, 172.) (b'Paul', 5, 173.)
 (b'Pit', 5, 164.)]
Ordenar por altura
[(b'James', 5, 156.) (b'Pit', 5, 164.) (b'Nail', 6, 172.)
 (b'Paul', 5, 173.)]


#### 3.  Agora ordene por classe e, em seguida, altura se as classes forem iguais. 

In [113]:
print("array original:")
print(students)
print("Ordenar por class e depois por altura caso a classe seja igual")
print(np.sort(students, order=['classe', 'altura']))

array original:
[(b'James', 5, 156.) (b'Nail', 6, 172.) (b'Paul', 5, 173.)
 (b'Pit', 5, 164.)]
Ordenar por class e depois por altura caso a classe seja igual
[(b'James', 5, 156.) (b'Pit', 5, 164.) (b'Paul', 5, 173.)
 (b'Nail', 6, 172.)]


#### 4.  Ordene os elementos do array Ids.
#### Ids = [1023, 5202, 6230, 1671, 1682, 5241, 4532]

In [114]:
Ids = [1023, 5202, 6230, 1671, 1682, 5241, 4532]
np.array(Ids)
np.sort(Ids)

array([1023, 1671, 1682, 4532, 5202, 5241, 6230])

#### 5.  Filtre nas posições especificadas:
#### m3 = [ 70 50 20 30 -11 60 50 40]
#### m4 =   [[1 5 0]
####            [3 2 5]
####            [8 7 6]]


In [115]:
m3 = [ 70, 50, 20, 30, -11, 60, 50, 40]
m4 = [[1,5,0],[3,2,5],[8,7,6]]

In [116]:
m3 = np.array(m3)
m3

array([ 70,  50,  20,  30, -11,  60,  50,  40])

In [117]:
m4 = np.array(m4).reshape(3,3)
m4

array([[1, 5, 0],
       [3, 2, 5],
       [8, 7, 6]])

5.1. Selecione o 4º elemento de m3.


In [118]:
m3[3]

30

5.2. Selecione o elemento central de m4 (2).


In [119]:
m4[1,1]

2

5.3. Selecione a 2ª coluna de m4.


In [120]:
m4[:,1]

array([5, 2, 7])

In [121]:
m4[:,1:2]

array([[5],
       [2],
       [7]])

5.4. Selecione apenas as duas primeiras linhas e duas primeiras colunas de m4.


In [122]:
m4[0:2,0:2]

array([[1, 5],
       [3, 2]])

5.5. Selecione 4 elementos de m3 a partir do elemento “20”.


In [123]:
m3[2:6]

array([ 20,  30, -11,  60])

5.6 Selecione última linha de m3.


In [124]:
m4[-1]

array([8, 7, 6])

In [125]:
m4[2:,:]

array([[8, 7, 6]])

5.7 Selecione a última coluna de m4.


In [126]:
m4[:,2:3]

array([[0],
       [5],
       [6]])

5.8. Selecione os últimos 2 elementos da última linha de m4.


In [127]:
m4[2][1:3]

array([7, 6])

5.9. Selecione a matriz 2x2 [[2,5],[7,6]].



In [128]:
m4[1:3,1:3]

array([[2, 5],
       [7, 6]])

#### 6. Construa o array m5 e responda às seguintes perguntas.
####      m5  = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [129]:
m5 = np.arange(0,11)
m5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

6.1. Altere os últimos 3 elemento de m5 para 33.


In [130]:
m5[8:11]=33
m5

array([ 0,  1,  2,  3,  4,  5,  6,  7, 33, 33, 33])

6.2. Crie um novo array com os primeiros 4 elementos de m5 e substitua por 40.


In [131]:
m5_new = m5.copy()
m5_new = m5_new[0:4]
m5_new

array([0, 1, 2, 3])

6.3. Imprima o array m5 e o novo array.


In [132]:
print(m5)
print(m5_new)

[ 0  1  2  3  4  5  6  7 33 33 33]
[0 1 2 3]


6.4. Selecione os valores de m5 maiores que 7.


In [133]:
m5[m5>7]

array([33, 33, 33])

6.5. Selecione os valores de m5 menores que 5.


In [134]:
m5[m5<7]

array([0, 1, 2, 3, 4, 5, 6])

6.6. Verifique quais os valores de m5 iguais a 7 ou a 10 (retorne uma matriz de valores booleanos).



In [135]:
a = m5 == 7  
b = m5 == 10
np.logical_or(a, b)

array([False, False, False, False, False, False, False,  True, False,
       False, False])

#### 7. Crie um array de 16 valores inteiros aleatórios entre 1 e 50 a que chamaremos m7. E crie o array m6 = [1,2,52,6,3,35,21,0,23,6,17,3,15,8,4,7]


In [136]:
m7 = np.random.randint(1,51,16)
m7

array([49, 38,  2, 12, 17, 20, 18, 46, 38, 40, 44, 47, 41, 21,  6, 35])

In [137]:
m6 = [1,2,52,6,3,35,21,0,23,6,17,3,15,8,4,7]
m6 = np.array(m6)
m6

array([ 1,  2, 52,  6,  3, 35, 21,  0, 23,  6, 17,  3, 15,  8,  4,  7])

7.1. Encontre o máximo para ambos os arrays.


In [138]:
m6.max()

52

In [139]:
m7.max()

49

7.2. Encontre o mínimo para ambos os arrays..


In [140]:
m6.min()

0

In [141]:
m7.min()

2

7.3. Encontre os valores de ambos os arrays que são menores que 7.


In [142]:
m6[m6<7]

array([1, 2, 6, 3, 0, 6, 3, 4])

In [143]:
m7[m7<7]

array([2, 6])

7.4. Encontre os valores de ambos os arrays que são maiores que 7.


In [144]:
m6[m6>7]

array([52, 35, 21, 23, 17, 15,  8])

In [145]:
m7[m7>7]

array([49, 38, 12, 17, 20, 18, 46, 38, 40, 44, 47, 41, 21, 35])

7.5. Calcule o logaritmo de ambos os arrays.


In [146]:
np.log(m6)

C:\Users\raquel.ribeiro\AppData\Local\Temp\ipykernel_25940\3920206033.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(m6)


array([0.        , 0.69314718, 3.95124372, 1.79175947, 1.09861229,
       3.55534806, 3.04452244,       -inf, 3.13549422, 1.79175947,
       2.83321334, 1.09861229, 2.7080502 , 2.07944154, 1.38629436,
       1.94591015])

In [147]:
np.log(m7)

array([3.8918203 , 3.63758616, 0.69314718, 2.48490665, 2.83321334,
       2.99573227, 2.89037176, 3.8286414 , 3.63758616, 3.68887945,
       3.78418963, 3.8501476 , 3.71357207, 3.04452244, 1.79175947,
       3.55534806])

7.6 Calcule a soma de um com o outro.


In [148]:
m6 + m7 

array([50, 40, 54, 18, 20, 55, 39, 46, 61, 46, 61, 50, 56, 29, 10, 42])

7.7 Calcule a subtração de um com o outro.


In [149]:
m6 - m7 

array([-48, -36,  50,  -6, -14,  15,   3, -46, -15, -34, -27, -44, -26,
       -13,  -2, -28])

7.8 Calcule a multiplicação de um com o outro.


In [150]:
m6 * m7 

array([ 49,  76, 104,  72,  51, 700, 378,   0, 874, 240, 748, 141, 615,
       168,  24, 245])

7.9 Calcule a divisão de um com o outro.

In [151]:
m6 /m7 

array([2.04081633e-02, 5.26315789e-02, 2.60000000e+01, 5.00000000e-01,
       1.76470588e-01, 1.75000000e+00, 1.16666667e+00, 0.00000000e+00,
       6.05263158e-01, 1.50000000e-01, 3.86363636e-01, 6.38297872e-02,
       3.65853659e-01, 3.80952381e-01, 6.66666667e-01, 2.00000000e-01])

7.10 Calcule o sen de ambos os arrays.


In [152]:
np.sin(m6)

array([ 0.84147098,  0.90929743,  0.98662759, -0.2794155 ,  0.14112001,
       -0.42818267,  0.83665564,  0.        , -0.8462204 , -0.2794155 ,
       -0.96139749,  0.14112001,  0.65028784,  0.98935825, -0.7568025 ,
        0.6569866 ])

In [153]:
np.sin(m7)

array([-0.95375265,  0.29636858,  0.90929743, -0.53657292, -0.96139749,
        0.91294525, -0.75098725,  0.90178835,  0.29636858,  0.74511316,
        0.01770193,  0.12357312, -0.15862267,  0.83665564, -0.2794155 ,
       -0.42818267])

7.11 Calcule o exponencial de ambos os arrays.


In [154]:
np.exp(m6)

array([2.71828183e+00, 7.38905610e+00, 3.83100800e+22, 4.03428793e+02,
       2.00855369e+01, 1.58601345e+15, 1.31881573e+09, 1.00000000e+00,
       9.74480345e+09, 4.03428793e+02, 2.41549528e+07, 2.00855369e+01,
       3.26901737e+06, 2.98095799e+03, 5.45981500e+01, 1.09663316e+03])

In [155]:
np.exp(m7)

array([1.90734657e+21, 3.18559318e+16, 7.38905610e+00, 1.62754791e+05,
       2.41549528e+07, 4.85165195e+08, 6.56599691e+07, 9.49611942e+19,
       3.18559318e+16, 2.35385267e+17, 1.28516001e+19, 2.58131289e+20,
       6.39843494e+17, 1.31881573e+09, 4.03428793e+02, 1.58601345e+15])