# Avaliação - Limpeza e transformação de dados em python
Cada pergunta da parte 1 vale 1 valor.<br>
A 2a parte vale no total 5 valores.<br>
A avaliação deverá ser enviada até as 22h do dia 20 de Dezembro de 2022 para o email raquel.ribeiro.prt@msft.cesae.pt.<br>
Boa avaliação!<br>

In [24]:
import pandas as pd
import numpy as np

## Parte 1

### NumPy

#### 1 - Crie a matriz mat 4x4 com valores de 1 a 16.

In [19]:
mat = np.arange (1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 2 - Crie um array com 30 elementos linearmente separados entre 1 e 12

In [20]:
arr = np.linspace(1, 12, num=30)
arr

array([ 1.        ,  1.37931034,  1.75862069,  2.13793103,  2.51724138,
        2.89655172,  3.27586207,  3.65517241,  4.03448276,  4.4137931 ,
        4.79310345,  5.17241379,  5.55172414,  5.93103448,  6.31034483,
        6.68965517,  7.06896552,  7.44827586,  7.82758621,  8.20689655,
        8.5862069 ,  8.96551724,  9.34482759,  9.72413793, 10.10344828,
       10.48275862, 10.86206897, 11.24137931, 11.62068966, 12.        ])

#### 3 - Volte a reproduzir o array da alínea 1, guardando-o numa variável. De seguida reproduza o seguinte output: <br>
 array([[ 1,  2,  3], <br>
       [ 5,  6,  7]]) <br>

In [21]:
mat[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

#### 4 - Obtenha um array com a soma de cada coluna da matriz mat.

In [22]:
np.sum(mat, axis=0)

array([28, 32, 36, 40])

#### 5 - Use o NumPy para gerar um array de 10 números aleatórios com amostragem na distribuição normal.

In [23]:
np.random.normal(size=10) 

array([-0.32821536,  1.01496347, -0.33213052,  1.12041315, -1.20462091,
        0.61976813, -0.50745788, -1.21371079, -1.1543586 , -0.59295592])

### Pandas

#### 6 - Crie as seguintes séries e imprima-as.
[1, 4, 3, 2, 10], [3, 3, 5, 2, 6]

In [28]:
d = pd.Series([1, 4, 3, 2, 10])
f = pd.Series([3, 3, 5, 2, 6])
print(d)
print(f)

0     1
1     4
2     3
3     2
4    10
dtype: int64
0    3
1    3
2    5
3    2
4    6
dtype: int64


#### 7 - Compare as duas séries no que diz respeito à sua igualdade

In [29]:
d==f

0    False
1    False
2    False
3     True
4    False
dtype: bool

#### 8 - Crie uma série que seja a soma das duas criadas na alínea 6

In [32]:
pd.Series([d,f]).sum()

0     4
1     7
2     8
3     4
4    16
dtype: int64

#### 9 - Crie o DataFrame 1 com os seguintes dados e mostre o seu output. Nota: o índice deverá iniciar em 'a' e seguir a ordem do alfabeto, <br>
{'vendedor': ['Bernardo', 'Rodrigo', 'Maria', 'Carla', 'Jorge', 'Vera', 'Ana', 'Vitor', 'Raquel', 'Arnalda'],<br>
'vendas_semana': [1200, 3000, 1500, np.nan, 9000, 1550, 10000, np.nan, 1700, 1900],<br>
'horario': ['PT', 'PT', 'PT', 'FT', 'FT', 'PT', 'FT', 'PT', 'PT', 'PT'],<br>
'ferias': ['sim', 'não', 'não', 'sim', 'não', 'não', 'não', 'sim', 'não', 'não']}<br>

In [48]:
df1 = pd.DataFrame({'vendedor': ['Bernardo', 'Rodrigo', 'Maria', 'Carla', 'Jorge', 'Vera', 'Ana', 'Vitor', 'Raquel', 'Arnalda'],
'vendas_semana': [1200, 3000, 1500, np.nan, 9000, 1550, 10000, np.nan, 1700, 1900],
'horario': ['PT', 'PT', 'PT', 'FT', 'FT', 'PT', 'FT', 'PT', 'PT', 'PT'],
'ferias': ['sim', 'não', 'não', 'sim', 'não', 'não', 'não', 'sim', 'não', 'não']}).sort_values(by=['vendedor'],ignore_index=True)
df1

vendedor  vendas_semana horario ferias
0       Ana        10000.0      FT    não
1   Arnalda         1900.0      PT    não
2  Bernardo         1200.0      PT    sim
3     Carla            NaN      FT    sim
4     Jorge         9000.0      FT    não
5     Maria         1500.0      PT    não
6    Raquel         1700.0      PT    não
7   Rodrigo         3000.0      PT    não
8      Vera         1550.0      PT    não
9     Vitor            NaN      PT    sim

#### 10 - Ordene o DataFrame1 por vendas da maior para a menor

In [49]:
df1.sort_values(by=['vendas_semana'], ascending=False)

vendedor  vendas_semana horario ferias
0       Ana        10000.0      FT    não
4     Jorge         9000.0      FT    não
7   Rodrigo         3000.0      PT    não
1   Arnalda         1900.0      PT    não
6    Raquel         1700.0      PT    não
8      Vera         1550.0      PT    não
5     Maria         1500.0      PT    não
2  Bernardo         1200.0      PT    sim
3     Carla            NaN      FT    sim
9     Vitor            NaN      PT    sim

#### 11 - Apresente a informação dos 3 melhores vendedores

In [71]:
df1.nlargest(3,['vendas_semana']).vendedor


0        Ana
4      Jorge
7    Rodrigo
Name: vendedor, dtype: object

#### 12 - Apresente os 3 piores vendedores não considerando aqueles que não têm vendas nem os que estiveram de férias

In [94]:

df2= (df1.loc[df1['ferias'] == 'não']).dropna()
df2.nsmallest(3,['vendas_semana']).vendedor


5     Maria
8      Vera
6    Raquel
Name: vendedor, dtype: object

#### 13 - Descubra a soma das vendas por tipo de horário

In [125]:
df1.groupby(['horario']).sum()


vendas_semana  comissao
horario                         
FT             19000.0     950.0
PT             10850.0     542.5

#### 14. Apague do DataFrame1 os valores nulos

df1 = df1.dropna()
df1

#### 15 - Sabendo que os vendedores recebem 5% de comissão, crie uma coluna no datafram com o nome "comissao" onde apresente o valor da comissão a receber pelo vendedor.

In [104]:
df1['comissao'] = df1['vendas_semana']*0.05
df1

vendedor  vendas_semana horario ferias  comissao
0       Ana        10000.0      FT    não     500.0
1   Arnalda         1900.0      PT    não      95.0
2  Bernardo         1200.0      PT    sim      60.0
4     Jorge         9000.0      FT    não     450.0
5     Maria         1500.0      PT    não      75.0
6    Raquel         1700.0      PT    não      85.0
7   Rodrigo         3000.0      PT    não     150.0
8      Vera         1550.0      PT    não      77.5

## Parte 2

Nesta parte será esperada a resolução, de forma crítica das seguintes tarefas:<br>
- crie 3 DataFrames, vendas, produto e cliente, a partir dos ficheiros csv fornecidos<br>
- crie um dataframe único que compile a informação dos 3 dataframes criados na tarefa anterior<br>
- apague as colunas que não forem necessárias para a análise<br>
- altere o nome das colunas para a sua tradução portuguesa<br>
- descubra o cliente que fez mais compras em valor <br>
- descubra o produto mais vendido em valor e o valor total de vendas do mesmo<br>
- descubra o produto menos vendido em valor<br>
- descubra a quantidade de produtos comprada pelo cliente que efetuou menos compras em quantidade<br>
- apresente o valor de vendas totais por loja<br>
Nota: o valor de vendas deve ser calculado a partir da quantidade e do seu preço.<br>

In [130]:
vendas = pd.read_csv('sales.csv')
produto = pd.read_csv('products.csv')
cliente = pd.read_csv('customer.csv')
vendas,produto,cliente

(   sale_id  c_id  p_id  product  qty store
 0        1     2     3  Monitor    2   ABC
 1        2     2     4      CPU    1   DEF
 2        3     1     3  Monitor    3   ABC
 3        4     4     2      RAM    2   DEF
 4        5     2     3  Monitor    3   ABC
 5        6     3     3  Monitor    2   DEF
 6        7     2     2      RAM    3   ABC
 7        8     3     2      RAM    2   DEF
 8        9     2     3  Monitor    2   ABC,
    p_id       product  price
 0     1     Hard Disk     80
 1     2           RAM     90
 2     3       Monitor     75
 3     4           CPU     55
 4     5      Keyboard     20
 5     6         Mouse     10
 6     7   Motherboard     50
 7     8  Power supply     20,
    c_id Customer
 0     1     Rabi
 1     2     Raju
 2     3     Alex
 3     4     Rani
 4     5     King
 5     7     Ronn
 6     8      Jem
 7     9      Tom)

In [146]:
vp= vendas.merge(produto, left_on='p_id', right_on='p_id')
vcp = v_p.merge(cliente, left_on='c_id', right_on='c_id')
vcp

sale_id  c_id  p_id product_x  qty store product_y  price Customer
0        1     2     3   Monitor    2   ABC   Monitor     75     Raju
1        5     2     3   Monitor    3   ABC   Monitor     75     Raju
2        9     2     3   Monitor    2   ABC   Monitor     75     Raju
3        2     2     4       CPU    1   DEF       CPU     55     Raju
4        7     2     2       RAM    3   ABC       RAM     90     Raju
5        3     1     3   Monitor    3   ABC   Monitor     75     Rabi
6        6     3     3   Monitor    2   DEF   Monitor     75     Alex
7        8     3     2       RAM    2   DEF       RAM     90     Alex
8        4     4     2       RAM    2   DEF       RAM     90     Rani

In [152]:
vcp = vcp.drop(columns=['product_y', 'sale_id','c_id', 'p_id'])

In [153]:
vcp.rename(columns = {'product_x':'produto', 'qty':'qt', 'store':'loja', 'price':'preço', 'Customer':'cliente'}, inplace = True)
vcp

produto  qt loja  preço cliente
0  Monitor   2  ABC     75    Raju
1  Monitor   3  ABC     75    Raju
2  Monitor   2  ABC     75    Raju
3      CPU   1  DEF     55    Raju
4      RAM   3  ABC     90    Raju
5  Monitor   3  ABC     75    Rabi
6  Monitor   2  DEF     75    Alex
7      RAM   2  DEF     90    Alex
8      RAM   2  DEF     90    Rani

In [175]:
vcp['valor'] = vcp['qt']*vcp['preço']

In [177]:
# descubra o cliente que fez mais compras em valor
vcp.groupby(['cliente']).sum().nlargest(1,['valor'])


qt  preço  valor
cliente                  
Raju     11    370    850

In [198]:
# descubra o produto mais vendido em valor e o valor total de vendas do mesmo
vcp.groupby(['produto']).sum().nlargest(1,['valor']).loc[:, ["valor"]]

valor
produto       
Monitor    900

In [200]:
# descubra o produto menos vendido em valor
vcp.groupby(['produto']).sum().nsmallest(1,['valor']).loc[:, ["valor"]]

valor
produto       
CPU         55

In [192]:
# descubra a quantidade de produtos comprada pelo cliente que efetuou menos compras em quantidade
vcp.groupby(['cliente']).sum().nsmallest(1,['qt']).loc[:, ["qt"]]

qt
cliente    
Rani      2

In [191]:
# apresente o valor de vendas totais por loja
vcp.groupby(['loja']).sum().loc[:, ["valor"]]


valor
loja       
ABC    1020
DEF     565