# NumPy Operações - Exercícios

In [1]:
import numpy as np

#### Repita o output apresentado:

mat=
>       array(
>           [[ 1,  2,  3,  4,  5],
>           [ 6,  7,  8,  9, 10],
>           [11, 12, 13, 14, 15],
>           [16, 17, 18, 19, 20],
>           [21, 22, 23, 24, 25]])


In [2]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### Siga as instruções

##### 1 - Obtenha a soma de todos os elementos de mat

In [3]:
mat.sum()

325

#### 2 - Obtenha o desvio padrão dos elementos de mat

In [4]:
mat.std()

7.211102550927978

In [7]:
np.std(mat)

7.211102550927978

##### 3 - Obtenha a soma de cada coluna de mat

In [5]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [6]:
sum(mat)

array([55, 60, 65, 70, 75])