# NumPy Indexação e Seleção - Exercícios

In [1]:
import numpy as np

#### Repita o output apresentado a partir de mat:

##### 1 -   mat=
>       array(
>           [[ 1,  2,  3,  4,  5],
>           [ 6,  7,  8,  9, 10],
>           [11, 12, 13, 14, 15],
>           [16, 17, 18, 19, 20],
>           [21, 22, 23, 24, 25]])


In [3]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### 2 -   
>       array(
>        [[12, 13, 14, 15],
>        [17, 18, 19, 20],
>        [22, 23, 24, 25]])


In [4]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

##### 3 -   20

In [5]:
mat[3,4]

20

##### 4 -   
>       array(
>           [[ 2],
>           [ 7],
>           [12]])

In [7]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

##### 5 -   array([21, 22, 23, 24, 25])

In [9]:
mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [10]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [11]:
mat[4]

array([21, 22, 23, 24, 25])

##### 6 -   
>           array([[16, 17, 18, 19, 20],
>          [21, 22, 23, 24, 25]])

In [16]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])